/** @type {import('pm2').StartOptions[]} */
const ROOT = __dirname;
const ENV_FILE = `${ROOT}/.env`;

module.exports = {
  apps: [
    {
      name: "legends-web",
      cwd: `${ROOT}/apps/web`,
      script: "node_modules/next/dist/bin/next",
      args: "dev -p 3000",
      interpreter: "node",
      env_file: ENV_FILE,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 1000,
      kill_timeout: 8000,
      treekill: true,
      out_file: `${ROOT}/logs/web.log`,
      error_file: `${ROOT}/logs/web.log`,
      merge_logs: true,
      time: true,
    },
    {
      name: "legends-ws",
      cwd: `${ROOT}/apps/ws`,
      script: "node_modules/tsx/dist/cli.mjs",
      args: "watch src/index.ts",
      interpreter: "node",
      env_file: ENV_FILE,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 1000,
      kill_timeout: 5000,
      treekill: true,
      out_file: `${ROOT}/logs/ws.log`,
      error_file: `${ROOT}/logs/ws.log`,
      merge_logs: true,
      time: true,
    },
    {
      name: "legends-bot",
      cwd: `${ROOT}/apps/bot`,
      script: "node_modules/tsx/dist/cli.mjs",
      args: "watch src/index.ts",
      interpreter: "node",
      env_file: ENV_FILE,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 1000,
      kill_timeout: 5000,
      treekill: true,
      out_file: `${ROOT}/logs/bot.log`,
      error_file: `${ROOT}/logs/bot.log`,
      merge_logs: true,
      time: true,
    },
  ],
};
