export const WS_EVENTS = {
  // server -> client
  MESSAGE_NEW: "message:new",
  MESSAGE_EDIT: "message:edit",
  MESSAGE_DELETE: "message:delete",
  REACTION_ADD: "reaction:add",
  REACTION_REMOVE: "reaction:remove",
  TOPIC_UPDATED: "topic:updated",
  PRESENCE_UPDATE: "presence:update",
  TYPING_START: "typing:start",
  TYPING_STOP: "typing:stop",
  USER_BANNED: "user:banned",
  USER_MUTED: "user:muted",
  POLL_UPDATED: "poll:updated",
  NOTIFICATION_NEW: "notification:new",
  SIDEBAR_UPDATE: "sidebar:update",
  HASHTAG_CLOUD_UPDATE: "hashtag:cloud:update",
  SYMBOLS_UPDATE: "symbols:update",
  DM_NEW: "dm:new",
  DM_EDIT: "dm:edit",
  DM_DELETE: "dm:delete",
  DM_READ: "dm:read",
  DM_REQUEST: "dm:request",
  DM_CONVERSATION_UPDATED: "dm:conversation:updated",
  TOPIC_MEMBERS_UPDATED: "topic:members:updated",

  // client -> server
  MESSAGE_SEND: "message:send",
  MESSAGE_EDIT_REQ: "message:edit:req",
  MESSAGE_DELETE_REQ: "message:delete:req",
  REACTION_TOGGLE: "reaction:toggle",
  TOPIC_READ: "topic:read",
  TOPIC_JOIN: "topic:join",
  TOPIC_LEAVE: "topic:leave",
  TYPING: "typing",
  BOT_KEYBOARD_CALLBACK: "bot:keyboard:callback",
  POLL_CREATE: "poll:create",
  POLL_VOTE: "poll:vote",
  POLL_CLOSE: "poll:close",

  // P2P signaling (bidirectional)
  P2P_JOIN: "p2p:join",
  P2P_JOINED: "p2p:joined",
  P2P_PEER_JOINED: "p2p:peer-joined",
  P2P_PEER_LEFT: "p2p:peer-left",
  P2P_OFFER: "p2p:offer",
  P2P_ANSWER: "p2p:answer",
  P2P_ICE: "p2p:ice",
  P2P_LEAVE: "p2p:leave",
  P2P_HEARTBEAT: "p2p:heartbeat",
  P2P_QUEUED: "p2p:queued",
  P2P_ADMITTED: "p2p:admitted",
  P2P_FALLBACK: "p2p:fallback",
  P2P_RESUME: "p2p:resume",
} as const;

export type WsEvent = (typeof WS_EVENTS)[keyof typeof WS_EVENTS];

export const REDIS_CHANNELS = {
  NOTIFICATION_NEW: "legends:notification:new",
  USER_BANNED: "legends:user:banned",
  USER_MUTED: "legends:user:muted",
  USER_UNMUTED: "legends:user:unmuted",
  USER_UNBANNED: "legends:user:unbanned",
  LOGIN_TOKEN_CONSUMED: "legends:login:token:consumed",
  BOT_MESSAGE_NEW: "legends:bot:message:new",
  BOT_MESSAGE_EDIT: "legends:bot:message:edit",
  BOT_MESSAGE_DELETE: "legends:bot:message:delete",
  BOT_NEW_MEMBER: "legends:bot:new_member",
  NOTIFICATION_BROADCAST: "legends:notification:broadcast",
  SYMBOLS_UPDATE: "legends:symbols:update",
  DM_MESSAGE_NEW: "legends:dm:message:new",
  DM_MESSAGE_EDIT: "legends:dm:message:edit",
  DM_MESSAGE_DELETE: "legends:dm:message:delete",
  DM_REQUEST_NEW: "legends:dm:request:new",
  DM_CONVERSATION_UPDATED: "legends:dm:conversation:updated",
  TOPIC_MEMBERS_UPDATED: "legends:topic:members:updated",
} as const;

export const REDIS_KEYS = {
  REVOKED_JTI: (jti: string) => `legends:jti:revoked:${jti}`,
  BAN_CACHE: (userId: string) => `legends:ban:${userId}`,
  MUTE_CACHE: (userId: string) => `legends:mute:${userId}`,
  USER_PROFILE: (userId: string) => `legends:user:profile:${userId}`,
} as const;
